# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJX1qy9d7MQbM-gv_mi2Djyemg5ThgLQ
"""

a=int(input("enter a number"))
if(a==0):
  print("the number is zero:",a)
elif a<0:
  print("the numbre is negative:",a)
else:
  print("the number is positive",a)

"""To check the weather is warm or cold

"""

x=int(input("enter the number"))
if(x<10):
  print("the weather is cold",x)
elif x>10 and x<40:
  print("the weather is warm",x)
else:
  print("the weather is hot",x)

"""grade program

"""

a=int(input("enter the number"))
if(a>90):
  print("grade A++",a)
elif a<90 and a>80:
  print("grade A",a)
elif a<70 and a<80:
  print("grade b",a)
elif a>60 and a<70:
  print("grade c",a)
else:
  print("fail",a)